// filename: cuda_backend.h
// purpose: Declares CUDA backend implementation for matmul execution.
// phase: Phase 2 - Real GPU
// last modified: 2026-04-29

#ifndef OPENGPU_LAB_BACKENDS_CUDA_CUDA_BACKEND_H_
#define OPENGPU_LAB_BACKENDS_CUDA_CUDA_BACKEND_H_

#include <cstddef>
#include <vector>

#include "runtime/backend.h"

namespace opengpu::backends::cuda {

/**
 * @brief CUDA backend implementation for runtime kernel launch requests.
 * @param None.
 * @return N/A.
 * @sideeffects Executes CUDA runtime operations.
 */
class CUDABackend final : public opengpu::runtime::Backend {
 public:
  CUDABackend() = default;
  ~CUDABackend() override = default;

  /**
   * @brief Launch entrypoint for runtime backend dispatch.
   * @param kernel Kernel descriptor.
   * @param launch Launch dimensions.
   * @return True on successful CUDA dispatch.
   * @sideeffects Performs host/device transfers and kernel launch.
   */
  bool launch(const opengpu::runtime::Kernel& kernel,
              const opengpu::runtime::LaunchConfig& launch) override;

  /**
   * @brief Executes square matrix multiplication through CUDA.
   * @param a Host matrix A in row-major layout.
   * @param b Host matrix B in row-major layout.
   * @param n Matrix dimension.
   * @param out Host output matrix C in row-major layout.
   * @return True if CUDA execution succeeds.
   * @sideeffects Allocates and frees CUDA device memory.
   */
  bool run_matmul(const std::vector<float>& a, const std::vector<float>& b, std::size_t n,
                  std::vector<float>* out) const;

  /**
   * @brief Sets pending matmul inputs used by launch().
   * @param a Host matrix A in row-major layout.
   * @param b Host matrix B in row-major layout.
   * @param n Matrix dimension.
   * @return None.
   * @sideeffects Replaces backend-owned pending inputs.
   */
  void set_pending_matmul_inputs(const std::vector<float>& a, const std::vector<float>& b,
                                 std::size_t n);

  /**
   * @brief Returns last launch output generated by launch().
   * @param None.
   * @return Copy of last matmul output.
   * @sideeffects None.
   */
  std::vector<float> last_output() const;

 private:
  std::vector<float> pending_a_;
  std::vector<float> pending_b_;
  std::vector<float> last_output_;
  std::size_t pending_n_{0U};
};

}  // namespace opengpu::backends::cuda

#endif  // OPENGPU_LAB_BACKENDS_CUDA_CUDA_BACKEND_H_
