// filename: rtl_sim_backend.h
// purpose: Declares RTL simulation backend implementation.
// phase: Phase 6 - Integration
// last modified: 2026-04-29

#ifndef OPENGPU_LAB_BACKENDS_RTL_SIM_BACKEND_H_
#define OPENGPU_LAB_BACKENDS_RTL_SIM_BACKEND_H_

#include <cstddef>
#include <vector>

#include "runtime/backend.h"

namespace opengpu::backends::rtl_sim {

/**
 * @brief Placeholder backend for Verilator-driven RTL simulation.
 * @param None.
 * @return N/A.
 * @sideeffects None in Phase 1.
 */
class RTLSimBackend final : public opengpu::runtime::Backend {
 public:
  RTLSimBackend() = default;
  ~RTLSimBackend() override = default;

  /**
   * @brief Stub launch for RTL simulation backend.
   * @param kernel Kernel descriptor.
   * @param launch Launch dimensions.
   * @return False until RTL backend integration exists.
   * @sideeffects None.
   */
  bool launch(const opengpu::runtime::Kernel& kernel,
              const opengpu::runtime::LaunchConfig& launch) override;

  /**
   * @brief Sets pending matmul inputs consumed by launch().
   * @param a Host matrix A in row-major layout.
   * @param b Host matrix B in row-major layout.
   * @param n Matrix dimension.
   * @return None.
   * @sideeffects Replaces backend-owned pending inputs.
   */
  void set_pending_matmul_inputs(const std::vector<float>& a, const std::vector<float>& b,
                                 std::size_t n);

  /**
   * @brief Returns last launch output generated by launch().
   * @param None.
   * @return Copy of last matmul output.
   * @sideeffects None.
   */
  std::vector<float> last_output() const;

 private:
  std::vector<float> pending_a_;
  std::vector<float> pending_b_;
  std::vector<float> last_output_;
  std::size_t pending_n_{0U};
};

}  // namespace opengpu::backends::rtl_sim

#endif  // OPENGPU_LAB_BACKENDS_RTL_SIM_BACKEND_H_
