// filename: cpu_backend.h
// purpose: Declares CPU backend implementation with matmul execution path.
// phase: Phase 3 - Runtime Abstraction
// last modified: 2026-04-29

#ifndef OPENGPU_LAB_BACKENDS_CPU_CPU_BACKEND_H_
#define OPENGPU_LAB_BACKENDS_CPU_CPU_BACKEND_H_

#include <cstddef>
#include <vector>

#include "runtime/backend.h"

namespace opengpu::backends::cpu {

/**
 * @brief Concrete backend for CPU execution path.
 * @param None.
 * @return N/A.
 * @sideeffects Executes workloads on host CPU.
 */
class CPUBackend final : public opengpu::runtime::Backend {
 public:
  CPUBackend() = default;
  ~CPUBackend() override = default;

  /**
   * @brief Launches kernel metadata on CPU backend.
   * @param kernel Kernel descriptor.
   * @param launch Launch dimensions.
   * @return True when launch metadata is accepted.
   * @sideeffects Placeholder launch bookkeeping only in Phase 1.
   */
  bool launch(const opengpu::runtime::Kernel& kernel,
              const opengpu::runtime::LaunchConfig& launch) override;

  /**
   * @brief Sets pending matmul inputs consumed by launch().
   * @param a Host matrix A in row-major layout.
   * @param b Host matrix B in row-major layout.
   * @param n Matrix dimension.
   * @return None.
   * @sideeffects Replaces backend-owned pending inputs.
   */
  void set_pending_matmul_inputs(const std::vector<float>& a, const std::vector<float>& b,
                                 std::size_t n);

  /**
   * @brief Returns last launch output generated by launch().
   * @param None.
   * @return Copy of last matmul output.
   * @sideeffects None.
   */
  std::vector<float> last_output() const;

 private:
  std::vector<float> pending_a_;
  std::vector<float> pending_b_;
  std::vector<float> last_output_;
  std::size_t pending_n_{0U};
};

}  // namespace opengpu::backends::cpu

#endif  // OPENGPU_LAB_BACKENDS_CPU_CPU_BACKEND_H_
